name: Test
on:
  push:
    branches:
      - feature/**
      - hotfix/**
      - depfu/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: module-cache
        with:
          path: node_modules
          key: modules-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.module-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run lint
